### ISSUE TITLE
The dataset link of CAS-VSR-W1k is broken.

### ISSUE THREAD

**Issue by Exgc** [VIPL-Audio-Visual-Speech-Understanding/VIPL-AVSU-Group#3]
The dataset link of [CAS-VSR-W1k(LRW1000)](http://vipl.ict.ac.cn/en/view_database.php?id=13)is broken.
Can you fix the link or provide a new download path?

At the same time, kindly remind you, I noticed that [the introduction page](http://vipl.ict.ac.cn/zygx/sjk/201810/t20181017_32714.html) of this dataset seems to be abnormal during the migration. Many words have lost letters, which seriously affects the reading.

**Comment by Fengdalu** [comment]
Please email lipreading@vipl.ict.ac.cn to apply for this dataset.
